### ISSUE TITLE
HKP & Keybase.io Support

### ISSUE THREAD

**Issue by indrora** [yahoo/end-to-end#24]
Awesome. Another standard for fetching keys. Keybase did it, so why not you? (Keybase actually is a slight bit easier to fetch from, and I'll get to it in a second)

There's a HUGE number of people who already have their pubkeys on keyservers such as MIT's `cryptonomicon.mit.edu` (commonly known as `pgp.mit.edu`). For instance, my personal key, `46652712679A49D0402DE45145118824A8B6F243` is available there.

HKP is defined [in an RFC](http://tools.ietf.org/html/draft-shaw-openpgp-hkp-00) which is pretty old.

It's also damn simple. There's two modes; Human (HTML) and Machine (text). To find my key using HKP, make a request like this:

http://pgp.mit.edu:11371/pks/lookup?search=46652712679A49D0402DE45145118824A8B6F243&op=index&options=mr

you get this: 

```
info:1:1
pub:46652712679A49D0402DE45145118824A8B6F243:1:4096:1280896106::
uid:Morgan Gangwere <indrora@earfolds.com>:1426360039::
uid:Morgan Gangwere <0.fractalus@gmail.com>:1330284891::
uid:Morgan Gangwere <morgan.gangwere@gmail.com>:1426360039::
uid:Morgan Gangwere (xmpp alias) <indrora@rows.io>:1426359975::
uid:Morgan Gangwere <indrora@indrora.homelinux.org>:1425539877::
uid:Morgan Gangwere (outlook alt) <morgan.gangwere@outlook.com>:1423102493::
uat::::
uat::::
```

To actually fetch the PGP key, change `op` to `fetch`:

http://pgp.mit.edu:11371/pks/lookup?search=46652712679A49D0402DE45145118824A8B6F243&op=fetch&options=mr

You get

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.5
Comment: Hostname: pgp.mit.edu

mQINBExY7GoBEACX3J4A37mHFDGDxJXG979mpVirCo+FD527zfDbMvr964173jmh6xKEEiVZ
BJc2lChosjH5UV6UXD3hrO6JrM0kN0pYcjdLsex0GlTercoz9HEPlh+zuC1hk1Mmq2kXcpYx
HiXHLRsUO9KzYnZL9+AozetuP7y6pRe4o0BPuHngoZ8dETqPDjeLI8Pcf0EYxsck7LMrrCEk
3HHBt7ExmcnP+/N0he9qZl8Ky8FXb3S/Kcffq+WnnQzj+goPeqi92TniLu3e/V8PvEPGIe0F
....
```

Port 80 is also used because firewalls. 

Keybase.io has a [straightforward API](https://keybase.io/docs/api/1.0/call/key/fetch) for this. You ask them for a key ID. They spit back an infoblob about that person, including a PGP bundle and some info about the person.

(tiny point: This is a blocker for me using it, or at this point, anyone using it who doesn't have some serious infrastructure)

**Comment by diracdeltas** [comment]
There's nothing wrong with HKP and I would happily take a pull request for it. However, for an MVP, it was overkill, since our intent was to demonstrate End to End working smoothly for Yahoo-to-Yahoo communication. The issue of compatibility with the existing GnuPG/Keybase/etc. userbase is an important one, but it needs a lot more thought than I've been able to give it so far.

Some considerations:
-  Unlike HKP, we need the ability to delete keys from the server.
- It's not acceptable for Yahoo to disclose the emails of every End to End user, so we can't sync our records with the public HKP pools.
- For Yahoo's use case, key lookups will primarily be by email address, not PGP ID.
- We don't really expose support for web of trust certifications.

**Comment by coruus** [comment]
@diracdeltas's comments are, of course, spot on. I wanted to amplify one point:

We don't want users to need to trust the operators of https://pgp.mit.edu, https://keybase.io, or https://yahoo.com in order to trust the validity of an email address -> userid binding. 

So we're collaborating with Google on building a "key transparency" system for users' keys.
We're not quite ready to release detailed design documents, but I'll put up some links to
relevant literature on our wiki.
1. Yahoo plans implement this before "officially supporting" End-to-End encryption
2. The API likely won't resemble the current API at all

This is kind of a "wontfix", except that we will fix the underlying problem:
Getting users' keys securely.

But we won't add support for anything that doesn't provide adequate security, except
strictly as necessary for developers to test the extension. (And "authoritative" keyservers
like pgp.mit.edu, keybase.io -- unless, perhaps, you validate the full proofs of identity, or
our toy "keyshop" don't provide adequate security for users.)

(I'll likely close this issue after I add the links I mentioned to the wiki.)

**Comment by indrora** [comment]
> We're collaborating with Google [...]

It seems you, in the process, have forgotten that there is a long-standing Security/Crypto-privacy community which has worked very hard to make the PGP trust system what it is today. It is _not_ perfect (When was the last time _you_ got invited to a keysigning party?) but what it does is create a decentralized, independent system.

There are no "Authoritative" HKP servers, only the ones that you know. The "official" SKS-keyserver one is a round-robin to a selection of the more beefy servers which can handle a lot of forward load. The Gossip network that makes the HKP system work is made up of literally _hundreds_ if not a few _thousand_ machines, each independently run. **This is what makes the HKP system resilient to attack: You can try and poison a few, but you will soon find that your efforts are in vain!**. 

There's issues I have with the API as it is described. What purpose does **deleting** keys have? What action does it **actually** do? If it simply scrubs the private factors from the key, _why bother?_.

> We don't want users to need to trust the operators of https://pgp.mit.edu, https://keybase.io, or https://yahoo.com in order to trust the validity of an email address -> userid binding.

Then **who shall they trust?** The system you guys are proposing hurts people who are even vaguely trying to escape centralized services by building their own. How am I, a user within what looks to be a walled garden, to verify a signed, or even encrypt+signed email from someone at the EFF? My professors? My senator? My lawyer? My _mother_?

How are you planning on handling the masses of privacy-minded individuals who currently use PGP on a daily basis, who _have_ taken the time to get their key signed, by multiple people, who are inevitably going to touch the people using this software? 

The extended trust that the PGP/HKP signing based system affords is enough for plenty of existing keys. Keybase, by using _lateral_ trust -- I know your twitter handle, and you can prove that that key and that twitter handle go together, thus giving me an out-of-band verification that you are who you say you are -- means you _as a person_ are doing the "Yes, I think this looks like the right person."

> This is kind of a "wontfix", except that we will fix the underlying problem: Getting users' keys securely.

**Have you never actually studied how PGP works?** Public keys should be easy and readily available, [like so](https://keybase.io/indrora/key.asc). There are known headers which people use to signify a means to provide 'A copy of my PGP pubkey block is here' (`X-pgp-pubkey-url` I think was one of the common ones, though I've seen `X-pgp-key-id`). The consistent, open availability of public keys is what gives PGP part of its strength. 

As for secret key hygiene? There's no one good answer. There's been plenty of attempts. So far, Keybase's usage of scrypt, and the consistent usage of 'gpg-agent' on the desktop have proven to be quite effective at doing what they say they want to do.

I'm closing this myself because apparently, Yahoo doesn't want to leverage the work of others, and instead wishes to play the "Not Invented Here" game.
