### ISSUE TITLE
require fewer permissions

### ISSUE THREAD

**Issue by maditya** [yahoo/end-to-end#77]
Currently due to the "tabs" permission, user gets a warning saying the extension has access to browsing history. Does chrome allow more granular permissions so the extension can open a new tab, but not have access to browsing history?

**Comment by happyfuncode** [comment]
Capturing @adon-at-work 's comments:

'For facebook key lookup, instead of asking during install-time, we can ask users for such a permission during runtime, i.e., when user actually clicks "FB key import".
(using optional permission: https://developer.chrome.com/extensions/permissions#manifest)'

'For "tabs" permission, I believe we can safely remove it without breaking anything.' - will need to test.  Any thoughts, @diracdeltas ?
